language: swift
podfile: Example/Podfile

osx_image: xcode10.2
xcode_sdk: iphonesimulator12.2

before_install:
  - rvm use system
  - brew install ruby
  - sudo gem install cocoapods -v '1.7.2'
  - pod repo update

script:
- xcodebuild clean build test -workspace Example/DKImagePickerControllerDemo.xcworkspace -scheme DKImagePickerControllerDemo -destination "platform=iOS Simulator,name=iPhone 7"
